SET NAMES utf8mb4;
SET time_zone = '+08:00';

USE `scenic_ai_guide`;

INSERT INTO `sys_admin` (
  `username`,
  `password`,
  `real_name`,
  `role`,
  `status`,
  `last_login_time`,
  `create_by`,
  `update_by`,
  `deleted`
) VALUES (
  'admin',
  '$2a$10$NFa2rTtrOkcyZJ1B9Me2nucj6Od4vX8PK4zP4ZAbm/G2v7wzNtGFO',
  'System Admin',
  'admin',
  1,
  NULL,
  NULL,
  NULL,
  0
);

INSERT INTO `tourist_user` (
  `phone`,
  `password`,
  `nickname`,
  `avatar`,
  `gender`,
  `interest_tags`,
  `status`,
  `last_login_time`,
  `create_by`,
  `update_by`,
  `deleted`
) VALUES (
  '13800000000',
  '$2a$10$ZovZked7NyRLmxQq/HYHhe8t1SXEMPfS.9TWFgeVAeQz/31K/FnR6',
  'Test Tourist',
  NULL,
  0,
  NULL,
  1,
  NULL,
  NULL,
  NULL,
  0
);

SET @avatar_render_config = '{"mouth":{"x":0.5,"y":0.13,"width":0.048,"height":0.018},"crop":{"x":0.5,"y":0.24,"scale":2.6},"breath":0.012,"blink":true}';

INSERT INTO `avatar_config` (
  `name`,
  `provider`,
  `gender`,
  `appearance`,
  `avatar_image`,
  `outfit`,
  `outfit_image`,
  `render_config`,
  `voice`,
  `speech_rate`,
  `welcome_text`,
  `is_default`,
  `enabled`,
  `remark`,
  `deleted`
) VALUES
  (
    '灵山文化女导游',
    '本地Canvas数字人',
    'FEMALE',
    '亲和、端庄、适合文化景区讲解的女性数字导游。',
    '/files/avatar/female_cultural_qipao_06.png',
    '淡雅旗袍',
    '/files/avatar/female_cultural_qipao_06.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '你好，我是你的灵山文化导游，可以为你讲解景点、规划路线，也可以识别你拍到的景观。',
    1,
    1,
    '默认文化特色女性形象',
    0
  ),
  (
    '花纹连衣裙女导游',
    '本地Canvas数字人',
    'FEMALE',
    '温和、自然、适合亲子和休闲游览讲解。',
    '/files/avatar/female_cultural_floral_05.png',
    '浅色花纹连衣裙',
    '/files/avatar/female_cultural_floral_05.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '欢迎来到景区，我会结合你的兴趣为你介绍沿途景点。',
    0,
    1,
    '女性文化休闲形象',
    0
  ),
  (
    '商务休闲女导游',
    '本地Canvas数字人',
    'FEMALE',
    '清爽、专业、适合服务咨询和综合导览。',
    '/files/avatar/female_business_casual_01.png',
    '白衬衫米色长裤',
    '/files/avatar/female_business_casual_01.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '你好，我可以帮你查询景点信息、开放时间和路线建议。',
    0,
    1,
    '女性商务休闲形象',
    0
  ),
  (
    '职业套装女导游',
    '本地Canvas数字人',
    'FEMALE',
    '稳重、正式，适合游客服务中心和管理型讲解场景。',
    '/files/avatar/female_business_suit_02.png',
    '黑色职业套装',
    '/files/avatar/female_business_suit_02.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '您好，我是景区 AI 导游，请告诉我你想了解的内容。',
    0,
    1,
    '女性职业形象',
    0
  ),
  (
    '休闲卫衣女导游',
    '本地Canvas数字人',
    'FEMALE',
    '轻松、年轻，适合家庭游客和轻量问答。',
    '/files/avatar/female_casual_hoodie_03.png',
    '白色卫衣牛仔裤',
    '/files/avatar/female_casual_hoodie_03.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '嗨，我可以陪你边逛边了解景点故事。',
    0,
    1,
    '女性休闲形象',
    0
  ),
  (
    '运动休闲女导游',
    '本地Canvas数字人',
    'FEMALE',
    '活力、轻快，适合路线推荐和运动型游客。',
    '/files/avatar/female_activewear_04.png',
    '浅紫运动上衣',
    '/files/avatar/female_activewear_04.png',
    @avatar_render_config,
    'xiaoyun',
    0,
    '我可以根据你的体力和时间推荐更合适的游览路线。',
    0,
    1,
    '女性运动形象',
    0
  ),
  (
    '灵山文化男导游',
    '本地Canvas数字人',
    'MALE',
    '沉稳、儒雅、适合文化景区深度讲解的男性数字导游。',
    '/files/avatar/male_cultural_tang_06.png',
    '灰色中式唐装',
    '/files/avatar/male_cultural_tang_06.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '你好，我是你的景区数字导游，可以为你讲解历史文化与参观路线。',
    0,
    1,
    '男性文化特色形象',
    0
  ),
  (
    '商务休闲男导游',
    '本地Canvas数字人',
    'MALE',
    '清爽、专业，适合标准导览和问答服务。',
    '/files/avatar/male_business_casual_01.png',
    '白衬衫米色长裤',
    '/files/avatar/male_business_casual_01.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '您好，我可以帮你查询景点、路线、服务设施和注意事项。',
    0,
    1,
    '男性商务休闲形象',
    0
  ),
  (
    '职业套装男导游',
    '本地Canvas数字人',
    'MALE',
    '正式、稳重，适合游客中心和综合咨询场景。',
    '/files/avatar/male_business_suit_02.png',
    '黑色职业西装',
    '/files/avatar/male_business_suit_02.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '欢迎来到景区，我会用简洁清晰的方式为你讲解。',
    0,
    1,
    '男性职业形象',
    0
  ),
  (
    '休闲卫衣男导游',
    '本地Canvas数字人',
    'MALE',
    '亲切、年轻，适合轻松问答和亲子游客。',
    '/files/avatar/male_casual_hoodie_03.png',
    '白色卫衣牛仔裤',
    '/files/avatar/male_casual_hoodie_03.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '我可以陪你轻松逛景区，也可以帮你快速找到想去的景点。',
    0,
    1,
    '男性休闲形象',
    0
  ),
  (
    '运动休闲男导游',
    '本地Canvas数字人',
    'MALE',
    '轻快、有活力，适合路线和体力友好型建议。',
    '/files/avatar/male_activewear_04.png',
    '灰色运动外套',
    '/files/avatar/male_activewear_04.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '告诉我你的游览时间，我可以帮你安排更顺路的路线。',
    0,
    1,
    '男性运动形象',
    0
  ),
  (
    '短袖休闲男导游',
    '本地Canvas数字人',
    'MALE',
    '阳光、清爽，适合夏季和轻量导览场景。',
    '/files/avatar/male_polo_casual_05.png',
    '蓝色 POLO 衫',
    '/files/avatar/male_polo_casual_05.png',
    @avatar_render_config,
    'xiaogang',
    0,
    '我可以快速回答你关心的路线、景点和服务问题。',
    0,
    1,
    '男性夏季休闲形象',
    0
  );

INSERT INTO `scenic` (
  `id`,
  `name`,
  `intro`,
  `address`,
  `open_time`,
  `ticket_info`,
  `traffic_info`,
  `service_phone`,
  `notice`,
  `cover_image`,
  `longitude`,
  `latitude`,
  `status`,
  `deleted`
) VALUES (
  1,
  '灵山胜境',
  '灵山胜境是以佛教文化、山水景观和大型文化演艺为特色的综合型景区，适合作为智慧导览、拍照识别、路线推荐和数字人讲解的示范场景。',
  '江苏省无锡市滨湖区马山灵山路1号',
  '08:30-17:00',
  '示范数据：成人票、优惠票以景区当天公告为准。',
  '可自驾或乘坐景区接驳交通抵达，节假日建议提前规划入园时间。',
  '400-000-0000',
  '示范数据仅用于系统演示，正式上线前请以官方资料包校验。',
  '/static/demo/scenic-lingshan.jpg',
  120.103200,
  31.424600,
  1,
  0
);

INSERT INTO `spot` (
  `id`,
  `scenic_id`,
  `name`,
  `alias`,
  `intro`,
  `history_culture`,
  `guide_text`,
  `tags`,
  `images`,
  `stay_minutes`,
  `suit_crowd`,
  `is_hot`,
  `longitude`,
  `latitude`,
  `status`,
  `deleted`
) VALUES
  (
    1,
    1,
    '灵山大佛',
    '大佛,无锡灵山大佛,释迦牟尼佛像',
    '灵山大佛是景区核心地标，佛像庄严开阔，是游客了解灵山佛教文化和拍照打卡的首选景点。',
    '灵山大佛以佛教文化展示和大型露天造像为特色，常作为景区文化讲解的起点。',
    '这里是灵山胜境的核心地标灵山大佛。参观时可以从佛像整体造型、广场轴线和周边山水格局理解景区的文化主题。建议在广场停留拍照，再沿动线继续前往九龙灌浴。',
    '经典,历史,文化,摄影,打卡',
    '/files/spot/spot-lingshan-buddha.webp',
    35,
    '首次到访游客,历史文化爱好者,摄影游客',
    1,
    120.103480,
    31.424850,
    1,
    0
  ),
  (
    2,
    1,
    '九龙灌浴',
    '九龙灌浴广场,九龙喷泉,灌浴',
    '九龙灌浴是景区重要表演与讲解点，适合结合佛教故事、音乐喷泉和广场空间进行沉浸式导览。',
    '九龙灌浴展示佛教传说故事，常用于讲解佛陀诞生意象和景区文化表达方式。',
    '这是九龙灌浴景点。讲解重点可以放在佛教传说、广场仪式感和喷泉表演节奏上。若游客时间有限，可优先观看整点表演，再前往梵宫。',
    '经典,文化,亲子,表演',
    '/files/spot/spot-jiulong-guanyu.webp',
    25,
    '亲子游客,文化体验游客',
    1,
    120.101980,
    31.424030,
    1,
    0
  ),
  (
    3,
    1,
    '灵山梵宫',
    '梵宫,灵山梵宫大厅,佛教艺术宫',
    '灵山梵宫以建筑空间、艺术装饰和文化展示见长，是深度游览与室内讲解的重要节点。',
    '梵宫集中呈现佛教艺术、建筑装饰和文化展陈，适合进行历史文化深度讲解。',
    '灵山梵宫适合慢节奏参观。游客可以关注建筑穹顶、壁画装饰和展陈空间，理解景区如何把传统文化转化为可体验的游览内容。',
    '历史,文化,深度,室内',
    '/files/spot/spot-lingshan-palace.webp',
    45,
    '历史文化爱好者,老人游客,深度游游客',
    1,
    120.100960,
    31.423520,
    1,
    0
  ),
  (
    4,
    1,
    '五印坛城',
    '坛城,五印坛,藏式建筑',
    '五印坛城具有鲜明建筑风格和宗教文化表达，适合拍照、建筑观察和文化补充讲解。',
    '五印坛城融合坛城意象与建筑艺术，是景区多元佛教文化展示的一部分。',
    '这里是五印坛城。建议从建筑色彩、空间层次和坛城象征意义三个角度理解，也很适合作为路线后半程的拍照停留点。',
    '摄影,建筑,文化,轻松',
    '/files/spot/spot-wuyin-tancheng.webp',
    30,
    '摄影游客,建筑爱好者,轻松游游客',
    1,
    120.099860,
    31.422980,
    1,
    0
  );

INSERT INTO `route` (
  `id`,
  `scenic_id`,
  `name`,
  `type`,
  `intro`,
  `estimate_minutes`,
  `suit_crowd`,
  `interest_tags`,
  `recommend_reason`,
  `notice`,
  `status`,
  `deleted`
) VALUES
  (
    1,
    1,
    '经典文化半日游',
    1,
    '覆盖灵山胜境最具代表性的核心景点，适合首次到访游客。',
    150,
    '首次到访游客,家庭游客',
    '经典,文化,摄影',
    '覆盖核心地标和代表性文化景点，适合第一次游览灵山胜境。',
    '节假日建议先确认九龙灌浴表演时间。',
    1,
    0
  ),
  (
    2,
    1,
    '历史文化深度游',
    4,
    '围绕佛教文化、建筑艺术和历史讲解安排较长停留。',
    210,
    '历史文化爱好者,深度游游客',
    '历史,文化,深度',
    '适合对历史文化感兴趣的游客，讲解内容更完整。',
    '梵宫室内参观时间较长，请预留体力。',
    1,
    0
  ),
  (
    3,
    1,
    '亲子轻松拍照游',
    2,
    '路线节奏较轻松，兼顾表演观看、拍照打卡和短时讲解。',
    120,
    '亲子游客,轻松游游客,摄影游客',
    '亲子,摄影,轻松,自然',
    '适合亲子和拍照需求，停留点清晰，步行压力较低。',
    '注意照看儿童，喷泉表演区域人流较多。',
    1,
    0
  );

INSERT INTO `route_spot` (
  `route_id`,
  `spot_id`,
  `sort_order`
) VALUES
  (1, 1, 1),
  (1, 2, 2),
  (1, 3, 3),
  (2, 1, 1),
  (2, 3, 2),
  (2, 4, 3),
  (3, 2, 1),
  (3, 4, 2),
  (3, 1, 3);

INSERT INTO `demo_switch` (
  `switch_key`,
  `enabled`,
  `remark`
) VALUES
  ('DASHBOARD_DEMO', 0, 'Initial dashboard demo switch'),
  ('REPORT_DEMO', 0, 'Initial report demo switch');

INSERT INTO `admin_feature_item` (
  `module_type`,
  `scenic_id`,
  `related_id`,
  `title`,
  `category`,
  `content`,
  `media_url`,
  `longitude`,
  `latitude`,
  `sort_order`,
  `status`,
  `remark`,
  `deleted`
) VALUES
  ('FACILITY', 1, NULL, '游客服务中心', '服务中心', '提供咨询、失物招领、应急协助和无障碍服务。', NULL, 120.102500, 31.424000, 1, 1, '示例设施', 0),
  ('FACILITY', 1, NULL, '停车场 P1', '停车场', '靠近主入口，适合自驾游客。', NULL, 120.104100, 31.423700, 2, 1, '示例设施', 0),
  ('TAG', NULL, NULL, '网红打卡点', '景点标签', '用于游客端筛选和运营推荐。', NULL, NULL, NULL, 1, 1, '示例标签', 0),
  ('TAG', NULL, NULL, '经典', '景点标签', '经典必游景点标签。', NULL, NULL, NULL, 2, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '历史', '景点标签', '历史文化景点标签。', NULL, NULL, NULL, 3, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '文化', '景点标签', '文化体验景点标签。', NULL, NULL, NULL, 4, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '摄影', '景点标签', '摄影打卡景点标签。', NULL, NULL, NULL, 5, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '亲子', '景点标签', '亲子家庭景点标签。', NULL, NULL, NULL, 6, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '自然', '景点标签', '自然风光景点标签。', NULL, NULL, NULL, 7, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '建筑', '景点标签', '建筑艺术景点标签。', NULL, NULL, NULL, 8, 1, '默认标签', 0),
  ('TAG', NULL, NULL, '表演', '景点标签', '演艺表演景点标签。', NULL, NULL, NULL, 9, 1, '默认标签', 0),
  ('ROUTE_TYPE', NULL, NULL, '经典必游', '1', '适合首次游览和官方推荐路线。', NULL, NULL, NULL, 1, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '亲子家庭', '2', '适合家庭、儿童和轻松互动路线。', NULL, NULL, NULL, 2, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '长者轻松', '3', '适合长者、低强度和少步行路线。', NULL, NULL, NULL, 3, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '历史文化', '4', '适合历史文化深度讲解路线。', NULL, NULL, NULL, 4, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '摄影打卡', '5', '适合拍照、打卡和视觉体验路线。', NULL, NULL, NULL, 5, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '休闲轻松', '6', '适合低强度、慢游和休闲路线。', NULL, NULL, NULL, 6, 1, '默认路线类型', 0),
  ('ROUTE_TYPE', NULL, NULL, '深度游览', '7', '适合完整游览和深度体验路线。', NULL, NULL, NULL, 7, 1, '默认路线类型', 0),
  ('ROUTE_INTEREST', NULL, NULL, '历史文化', 'history', '游客兴趣编码 history。', NULL, NULL, NULL, 1, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '自然风光', 'nature', '游客兴趣编码 nature。', NULL, NULL, NULL, 2, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '摄影打卡', 'photo', '游客兴趣编码 photo。', NULL, NULL, NULL, 3, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '亲子家庭', 'parent', '游客兴趣编码 parent。', NULL, NULL, NULL, 4, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '文化体验', 'culture', '游客兴趣编码 culture。', NULL, NULL, NULL, 5, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '经典必游', 'classic', '游客兴趣编码 classic。', NULL, NULL, NULL, 6, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '轻松休闲', 'leisure', '游客兴趣编码 leisure。', NULL, NULL, NULL, 7, 1, '默认兴趣标签', 0),
  ('ROUTE_INTEREST', NULL, NULL, '深度游览', 'deep', '游客兴趣编码 deep。', NULL, NULL, NULL, 8, 1, '默认兴趣标签', 0),
  ('ROUTE_CONTENT', 1, 1, '经典文化半日游讲解词', '讲解词', '欢迎体验经典文化半日游，本路线覆盖灵山大佛、九龙灌浴和灵山梵宫。', NULL, NULL, NULL, 1, 1, '路线关联内容示例', 0),
  ('PROMPT', NULL, NULL, '温和专业导游人设', '通用问答', '你是一名温和、专业、简洁的景区 AI 导游，回答时优先结合景区知识库。', NULL, NULL, NULL, 1, 1, 'Prompt 示例', 0),
  ('SENSITIVE_WORD', NULL, NULL, '辱骂词过滤', '拦截', '命中后回复：请文明交流，我可以继续为你介绍景区信息。', NULL, NULL, NULL, 1, 1, '敏感词示例', 0),
  ('PUSH_MESSAGE', 1, NULL, '九龙灌浴表演提醒', '全体游客', '九龙灌浴表演即将开始，请注意现场秩序并保管随身物品。', NULL, NULL, NULL, 1, 1, '推送示例', 0),
  ('ACHIEVEMENT', 1, NULL, '文化探索者', '打卡成就', '完成灵山大佛、九龙灌浴、灵山梵宫三个景点打卡后获得。', NULL, NULL, NULL, 1, 1, '成就示例', 0),
  ('VOICE', NULL, NULL, '温柔女声', 'TTS 音色', '适合亲子、轻松导览场景，语速中等。', NULL, NULL, NULL, 1, 1, '音色示例', 0),
  ('TODO', NULL, NULL, '补齐夜游路线问答', '知识库待办', '感受度报告中出现夜游路线问题，需要补充知识库文档。', NULL, NULL, NULL, 1, 1, '待办示例', 0);
